[pytest]
addopts =
    -ra
    --tb=short
    --log-cli-level=ERROR
    --log-level=DEBUG
    --log-disable=aiosqlite
    --log-disable=httpx
    --log-disable=python_multipart
    --cov=app
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=50

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
