"""added admin primitives

Revision ID: 9d77f867f7fb
Revises: 9f6aad112955
Create Date: 2025-07-29 10:53:16.091288

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d77f867f7fb"
down_revision = "9f6aad112955"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celebrities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("celebrities_pkey")),
    )
    op.create_index("ux_celebrities_name_lower", "celebrities", [sa.literal_column("lower(name)")], unique=True)
    op.create_table(
        "funnels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("funnels_pkey")),
    )
    op.create_index("ux_funnels_name_lower", "funnels", [sa.literal_column("lower(name)")], unique=True)
    op.create_table(
        "site_names",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("site_names_pkey")),
    )
    op.create_index("ux_site_names_name_lower", "site_names", [sa.literal_column("lower(name)")], unique=True)
    op.add_column("web_master_tasks", sa.Column("funnel_id", sa.Integer(), nullable=True))
    op.add_column("web_master_tasks", sa.Column("site_name_id", sa.Integer(), nullable=True))
    op.add_column("web_master_tasks", sa.Column("celebrity_id", sa.Integer(), nullable=True))
    op.add_column("web_master_tasks", sa.Column("geo_id", sa.Integer(), nullable=True))
    op.create_foreign_key(op.f("web_master_tasks_funnel_id_fkey"), "web_master_tasks", "funnels", ["funnel_id"], ["id"])
    op.create_foreign_key(
        op.f("web_master_tasks_site_name_id_fkey"), "web_master_tasks", "site_names", ["site_name_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("web_master_tasks_celebrity_id_fkey"), "web_master_tasks", "celebrities", ["celebrity_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("web_master_tasks_geo_id_fkey"), "web_master_tasks", "geos", ["geo_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("web_master_tasks_geo_id_fkey"), "web_master_tasks", type_="foreignkey")
    op.drop_constraint(op.f("web_master_tasks_celebrity_id_fkey"), "web_master_tasks", type_="foreignkey")
    op.drop_constraint(op.f("web_master_tasks_site_name_id_fkey"), "web_master_tasks", type_="foreignkey")
    op.drop_constraint(op.f("web_master_tasks_funnel_id_fkey"), "web_master_tasks", type_="foreignkey")
    op.drop_column("web_master_tasks", "geo_id")
    op.drop_column("web_master_tasks", "celebrity_id")
    op.drop_column("web_master_tasks", "site_name_id")
    op.drop_column("web_master_tasks", "funnel_id")
    op.drop_index("ux_site_names_name_lower", table_name="site_names")
    op.drop_table("site_names")
    op.drop_index("ux_funnels_name_lower", table_name="funnels")
    op.drop_table("funnels")
    op.drop_index("ux_celebrities_name_lower", table_name="celebrities")
    op.drop_table("celebrities")
    # ### end Alembic commands ###
