"""remove_titer_field_from_creative_celebrities

Revision ID: dd963849a1bd
Revises: f181f9439170
Create Date: 2025-09-22 16:25:07.416027

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd963849a1bd"
down_revision = "f181f9439170"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("creative_celebrities", "titer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creative_celebrities", sa.Column("titer", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
