"""made points float

Revision ID: 55bd8f7af5b0
Revises: f5c2236a6f41
Create Date: 2025-07-30 19:13:56.120209

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55bd8f7af5b0"
down_revision = "f5c2236a6f41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "web_master_difficulty_levels", "points", existing_type=sa.INTEGER(), type_=sa.Float(), existing_nullable=False
    )
    op.bulk_insert(
        sa.table(
            "web_master_difficulty_levels",
            sa.column("name", sa.String),
            sa.column("points", sa.Float),
        ),
        [
            {
                "name": "Very Low",
                "points": 0.5},
            {
                "name": "Low",
                "points": 1},
            {
                "name": "Medium",
                "points": 2},
            {
                "name": "Hard",
                "points": 4},
            {
                "name": "Very Hard",
                "points": 8},
        ],
    )

    op.bulk_insert(
        sa.table(
            "web_master_task_types",
            sa.column("name", sa.String),
        ),
        [
            {
                "name": "create"},
            {
                "name": "edit"},
            {
                "name": "duplicate"},
            {
                "name": "transfer"},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "web_master_difficulty_levels", "points", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.execute(
        "DELETE FROM web_master_task_types "
        "WHERE name IN ('create','edit','duplicate','transfer');"
    )
    op.execute(
        "DELETE FROM web_master_difficulty_levels "
        "WHERE name IN ('Very Low','Low','Medium','Hard','Very Hard');"
    )
    # ### end Alembic commands ###


