"""add_assistant_reference_to_media_buyer

Revision ID: 03087aaed981
Revises: 8172a211dabd
Create Date: 2025-10-01 18:46:36.270230

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03087aaed981"
down_revision = "8172a211dabd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_buyers", sa.Column("assistant_reference_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("media_buyers_assistant_reference_id_fkey"),
        "media_buyers",
        "media_buyers",
        ["assistant_reference_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("media_buyers_assistant_reference_id_fkey"), "media_buyers", type_="foreignkey")
    op.drop_column("media_buyers", "assistant_reference_id")
    # ### end Alembic commands ###
