"""update_creative_format_to_enum

Revision ID: 8172a211dabd
Revises: f953814be582
Create Date: 2025-09-24 12:16:49.249766

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8172a211dabd"
down_revision = "f953814be582"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type if it doesn't exist
    creative_format_enum = sa.Enum(
        "SQUARE", "VERTICAL", "HORIZONTAL", "OTHER", "RATIO_5_TO_4", "RATIO_4_TO_5", 
        name="creativeformat"
    )
    try:
        creative_format_enum.create(op.get_bind())
    except Exception:
        # Enum already exists, skip
        pass
    
    # Update existing data: map string values to enum values
    op.execute("""
        UPDATE creatives 
        SET format = CASE 
            WHEN format = 'square' THEN 'SQUARE'
            WHEN format = 'vertical' THEN 'VERTICAL'
            WHEN format = 'horizontal' THEN 'HORIZONTAL'
            WHEN format = 'other' THEN 'OTHER'
            WHEN format = 'ratio_5_to_4' THEN 'RATIO_5_TO_4'
            WHEN format = 'ratio_4_to_5' THEN 'RATIO_4_TO_5'
            ELSE 'OTHER'
        END
    """)
    
    # Alter the column type
    op.alter_column(
        "creatives",
        "format",
        existing_type=sa.VARCHAR(length=50),
        type_=creative_format_enum,
        existing_nullable=True,
        postgresql_using="format::creativeformat"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Alter the column back to VARCHAR
    op.alter_column(
        "creatives",
        "format",
        existing_type=sa.Enum(
            "SQUARE", "VERTICAL", "HORIZONTAL", "OTHER", "RATIO_5_TO_4", "RATIO_4_TO_5", name="creativeformat"
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    
    # Drop the enum type
    creative_format_enum = sa.Enum(
        "SQUARE", "VERTICAL", "HORIZONTAL", "OTHER", "RATIO_5_TO_4", "RATIO_4_TO_5", 
        name="creativeformat"
    )
    try:
        creative_format_enum.drop(op.get_bind())
    except Exception:
        # Enum doesn't exist or can't be dropped, skip
        pass
    # ### end Alembic commands ###
