"""add_creative_id_to_media_files_and_remove_file_fields_from_creative

Revision ID: 36f242c392b7
Revises: d411e9e4d832
Create Date: 2025-09-12 00:53:53.069011

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36f242c392b7"
down_revision = "d411e9e4d832"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("creatives", "file_key")
    op.drop_column("creatives", "file_url")
    op.add_column("media_files", sa.Column("creative_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("media_files_creative_id_fkey"), "media_files", "creatives", ["creative_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("media_files_creative_id_fkey"), "media_files", type_="foreignkey")
    op.drop_column("media_files", "creative_id")
    op.add_column("creatives", sa.Column("file_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("creatives", sa.Column("file_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
