"""added soft delete for tasks

Revision ID: 25f1b85fdb71
Revises: 27a3694a0e79
Create Date: 2025-06-21 13:52:15.448180

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25f1b85fdb71"
down_revision = "27a3694a0e79"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "designer_tasks",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("designer_tasks", "is_deleted")
    # ### end Alembic commands ###
