"""added soft delete for geo

Revision ID: 9f6aad112955
Revises: b9c22e75231b
Create Date: 2025-07-25 11:12:29.549097

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f6aad112955"
down_revision = "b9c22e75231b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geos", sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("geos", "is_deleted")
    # ### end Alembic commands ###
