"""added multi leads table

Revision ID: 54ccf2167f01
Revises: 5aecdbb85fe4
Create Date: 2025-07-03 22:17:07.662178

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54ccf2167f01"
down_revision = "5aecdbb85fe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "designers_team_leads",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("designer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["designer_id"], ["designers.id"], name=op.f("designers_team_leads_designer_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["designers_teams.id"], name=op.f("designers_team_leads_team_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("team_id", "designer_id", name=op.f("designers_team_leads_pkey")),
    )
    op.drop_constraint("designers_teams_lead_id_fkey", "designers_teams", type_="foreignkey")
    op.drop_column("designers_teams", "lead_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("designers_teams", sa.Column("lead_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("designers_teams_lead_id_fkey", "designers_teams", "designers", ["lead_id"], ["id"])
    op.drop_table("designers_team_leads")
    # ### end Alembic commands ###
