"""added description media

Revision ID: 2a25b10bf0f5
Revises: ddefede140f2
Create Date: 2025-08-12 21:19:37.247641

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a25b10bf0f5"
down_revision = "ddefede140f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_files", sa.Column("is_description", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_files", "is_description")
    # ### end Alembic commands ###
