"""added jwt version

Revision ID: 140258104c76
Revises: 5d2bda10c7d7
Create Date: 2025-07-16 00:32:42.443127

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "140258104c76"
down_revision = "5d2bda10c7d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("jwt_version", sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "jwt_version")
    # ### end Alembic commands ###
