"""Updated Task History

Revision ID: e8c0d3d8aa23
Revises: e2eaf16873a7
Create Date: 2025-07-11 17:45:31.400274

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e8c0d3d8aa23"
down_revision = "e2eaf16873a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("designer_task_history", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "designer_task_history", sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true(), )
        )
    # ### end Alembic commands ###
    op.execute("UPDATE designer_task_history SET active = false")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("designer_task_history", "active")
    op.drop_column("designer_task_history", "description")
    # ### end Alembic commands ###
