"""updated task history model

Revision ID: 62b5d7cdd6ed
Revises: 54ccf2167f01
Create Date: 2025-07-04 12:07:48.616015

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62b5d7cdd6ed"
down_revision = "54ccf2167f01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("designer_task_history_buyer_id_fkey", "designer_task_history", type_="foreignkey")
    op.drop_constraint("designer_task_history_lead_id_fkey", "designer_task_history", type_="foreignkey")
    op.drop_constraint("designer_task_history_assigned_designer_id_fkey", "designer_task_history", type_="foreignkey")
    op.drop_column("designer_task_history", "assigned_designer_id")
    op.drop_column("designer_task_history", "lead_id")
    op.drop_column("designer_task_history", "buyer_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("designer_task_history", sa.Column("buyer_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("designer_task_history", sa.Column("lead_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "designer_task_history", sa.Column("assigned_designer_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "designer_task_history_assigned_designer_id_fkey",
        "designer_task_history",
        "designers",
        ["assigned_designer_id"],
        ["id"],
    )
    op.create_foreign_key(
        "designer_task_history_lead_id_fkey", "designer_task_history", "designers", ["lead_id"], ["id"]
    )
    op.create_foreign_key(
        "designer_task_history_buyer_id_fkey", "designer_task_history", "media_buyers", ["buyer_id"], ["id"]
    )
    # ### end Alembic commands ###
