"""added_creatives_and_language_models

Revision ID: 5d3f65c33135
Revises: 2a25b10bf0f5
Create Date: 2025-09-11 23:59:23.907087

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d3f65c33135"
down_revision = "2a25b10bf0f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("languages_pkey")),
        sa.UniqueConstraint("code", name=op.f("languages_code_key")),
    )
    op.create_index("ux_languages_code_lower", "languages", [sa.literal_column("lower(code)")], unique=True)
    op.create_table(
        "creatives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=True),
        sa.Column("celebrity_id", sa.Integer(), nullable=True),
        sa.Column("subtitles", sa.Text(), nullable=True),
        sa.Column("plashka", sa.String(length=255), nullable=True),
        sa.Column("ad_name", sa.String(length=100), nullable=True),
        sa.Column("file_url", sa.String(length=255), nullable=True),
        sa.Column("file_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["celebrity_id"], ["celebrities.id"], name=op.f("creatives_celebrity_id_fkey")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["designer_tasks.id"], name=op.f("creatives_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("creatives_pkey")),
        sa.UniqueConstraint("ad_name", name=op.f("creatives_ad_name_key")),
    )
    op.add_column("designer_tasks", sa.Column("language_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("designer_tasks_language_id_fkey"),
        "designer_tasks",
        "languages",
        ["language_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("designer_tasks_language_id_fkey"), "designer_tasks", type_="foreignkey")
    op.drop_column("designer_tasks", "language_id")
    op.drop_table("creatives")
    op.drop_index("ux_languages_code_lower", table_name="languages")
    op.drop_table("languages")
    # ### end Alembic commands ###
