"""added notification logic

Revision ID: ddefede140f2
Revises: 55bd8f7af5b0
Create Date: 2025-08-05 17:21:03.255994

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddefede140f2"
down_revision = "55bd8f7af5b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("SUCCESS", "FAILURE", name="notificationstatus"), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["designer_tasks.id"], name=op.f("notification_queue_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_queue_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_queue")
    # ### end Alembic commands ###
