"""added tg

Revision ID: f490433d731d
Revises: e2eaf16873a7
Create Date: 2025-07-09 17:34:00.131371

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f490433d731d"
down_revision = "e2eaf16873a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("telegram_token", sa.String(length=36), nullable=True))
    op.create_unique_constraint(op.f("users_telegram_chat_id_key"), "users", ["telegram_chat_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_telegram_chat_id_key"), "users", type_="unique")
    op.drop_column("users", "telegram_token")
    op.drop_column("users", "telegram_chat_id")
    # ### end Alembic commands ###
