"""add_keitaro_config_user_id_to_creatives

Revision ID: 6cdba9434678
Revises: a2c5f4e1b9cd
Create Date: 2025-10-29 16:52:42.151208

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6cdba9434678"
down_revision = "a2c5f4e1b9cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("keitaro_config_user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("creatives_keitaro_config_user_id_fkey"), "creatives", "users", ["keitaro_config_user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("creatives_keitaro_config_user_id_fkey"), "creatives", type_="foreignkey")
    op.drop_column("creatives", "keitaro_config_user_id")
    # ### end Alembic commands ###
