"""added geo table

Revision ID: b9c22e75231b
Revises: c95587fc2468
Create Date: 2025-07-23 00:18:32.394412

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b9c22e75231b"
down_revision = "c95587fc2468"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("geos_pkey")),
        sa.UniqueConstraint("code", name=op.f("geos_code_key")),
    )
    op.add_column("designer_tasks", sa.Column("geo_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("designer_tasks_geo_id_fkey"), "designer_tasks", "geos", ["geo_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("designer_tasks", "geo_code")
    op.drop_column("designer_tasks", "geo_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("designer_tasks", sa.Column("geo_name", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("designer_tasks", sa.Column("geo_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(op.f("designer_tasks_geo_id_fkey"), "designer_tasks", type_="foreignkey")
    op.drop_column("designer_tasks", "geo_id")
    op.drop_table("geos")
    # ### end Alembic commands ###
