"""add_keitaro_config_table

Revision ID: ce9a760242d8
Revises: a1e27506a2f1
Create Date: 2025-09-15 22:38:07.853621

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce9a760242d8"
down_revision = "a1e27506a2f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keitaro_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("keitaro_configs_pkey")),
    )
    op.add_column("media_buyers_teams", sa.Column("keitaro_config_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("media_buyers_teams_keitaro_config_id_fkey"),
        "media_buyers_teams",
        "keitaro_configs",
        ["keitaro_config_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("media_buyers_teams_keitaro_config_id_fkey"), "media_buyers_teams", type_="foreignkey")
    op.drop_column("media_buyers_teams", "keitaro_config_id")
    op.drop_table("keitaro_configs")
    # ### end Alembic commands ###
