"""squash migration

Revision ID: 55e071fe989d
Revises:
Create Date: 2025-06-05 15:44:07.203340

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55e071fe989d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "difficulty_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("is_inactive", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("difficulty_levels_pkey")),
    )
    op.create_table(
        "task_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_inactive", sa.Boolean(), nullable=True),
        sa.Column("evaluation_required", sa.Boolean(), nullable=True),
        sa.Column("evaluation_required_by_roles", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("task_types_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "media_buyer",
                "web_master",
                "user",
                "lead_web_master",
                "lead_media_buyer",
                "lead_designer",
                "designer",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("username", name=op.f("users_username_key")),
    )
    op.create_table(
        "web_master_difficulty_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("web_master_difficulty_levels_pkey")),
        sa.UniqueConstraint("name", name=op.f("web_master_difficulty_levels_name_key")),
    )
    op.create_table(
        "web_master_task_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("web_master_task_types_pkey")),
        sa.UniqueConstraint("name", name=op.f("web_master_task_types_name_key")),
    )
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name=op.f("admins_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("admins_pkey")),
    )
    op.create_table(
        "designers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_lead_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name=op.f("designers_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_lead_id"], ["designers.id"], name=op.f("designers_team_lead_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("designers_pkey")),
    )
    op.create_table(
        "media_buyers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_lead_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name=op.f("media_buyers_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_lead_id"], ["media_buyers.id"], name=op.f("media_buyers_team_lead_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("media_buyers_pkey")),
    )
    op.create_table(
        "web_masters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_lead_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["users.id"], name=op.f("web_masters_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_lead_id"], ["web_masters.id"], name=op.f("web_masters_team_lead_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("web_masters_pkey")),
    )
    op.create_table(
        "designers_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["designers.id"], name=op.f("designers_teams_lead_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("designers_teams_pkey")),
    )
    op.create_table(
        "media_buyers_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("responsible_designer", sa.Integer(), nullable=True),
        sa.Column("responsible_web_master", sa.Integer(), nullable=True),
        sa.Column("prefix", sa.String(length=100), nullable=True),
        sa.Column("custom_task_start_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["media_buyers.id"], name=op.f("media_buyers_teams_lead_id_fkey")),
        sa.ForeignKeyConstraint(
            ["responsible_designer"], ["designers.id"], name=op.f("media_buyers_teams_responsible_designer_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["responsible_web_master"], ["web_masters.id"], name=op.f("media_buyers_teams_responsible_web_master_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("media_buyers_teams_pkey")),
    )
    op.create_table(
        "web_masters_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["lead_id"], ["web_masters.id"], name=op.f("web_masters_teams_lead_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("web_masters_teams_pkey")),
    )
    op.create_table(
        "designer_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_status",
            sa.Enum(
                "DRAFT",
                "WAITING_TO_ASSIGN",
                "WAITING_TO_START",
                "IN_PROGRESS",
                "REQUESTED_CHANGES",
                "UNDER_TL_REVIEW",
                "UNDER_BUYER_REVIEW",
                "COMPLETED",
                name="designertaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("task_type_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("is_high_priority", sa.Boolean(), nullable=True),
        sa.Column("is_operational", sa.Boolean(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("buyer_team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to_id"], ["designers.id"], name=op.f("designer_tasks_assigned_to_id_fkey")),
        sa.ForeignKeyConstraint(
            ["buyer_team_id"], ["media_buyers_teams.id"], name=op.f("designer_tasks_buyer_team_id_fkey")
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], name=op.f("designer_tasks_created_by_id_fkey")),
        sa.ForeignKeyConstraint(["task_type_id"], ["task_types.id"], name=op.f("designer_tasks_task_type_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("designer_tasks_pkey")),
    )
    op.create_table(
        "designers_team_members",
        sa.Column("designer_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["designer_id"], ["designers.id"], name=op.f("designers_team_members_designer_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["designers_teams.id"], name=op.f("designers_team_members_team_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("designer_id", "team_id", name=op.f("designers_team_members_pkey")),
    )
    op.create_table(
        "media_buyers_team_members",
        sa.Column("media_buyer_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_buyer_id"],
            ["media_buyers.id"],
            name=op.f("media_buyers_team_members_media_buyer_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["media_buyers_teams.id"],
            name=op.f("media_buyers_team_members_team_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("media_buyer_id", "team_id", name=op.f("media_buyers_team_members_pkey")),
    )
    op.create_table(
        "web_master_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_status",
            sa.Enum(
                "DRAFT",
                "WAITING_TO_ASSIGN",
                "WAITING_TO_START",
                "IN_PROGRESS",
                "REQUESTED_CHANGES",
                "UNDER_TL_REVIEW",
                "UNDER_BUYER_REVIEW",
                "COMPLETED",
                name="webmastertaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("task_type_id", sa.Integer(), nullable=True),
        sa.Column("task_points", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("is_high_priority", sa.Boolean(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("buyer_team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"], ["web_masters.id"], name=op.f("web_master_tasks_assigned_to_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_team_id"], ["media_buyers_teams.id"], name=op.f("web_master_tasks_buyer_team_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["media_buyers.id"], name=op.f("web_master_tasks_created_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["task_type_id"], ["web_master_task_types.id"], name=op.f("web_master_tasks_task_type_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("web_master_tasks_pkey")),
    )
    op.create_table(
        "web_masters_team_members",
        sa.Column("web_master_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["web_masters_teams.id"],
            name=op.f("web_masters_team_members_team_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["web_master_id"],
            ["web_masters.id"],
            name=op.f("web_masters_team_members_web_master_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("web_master_id", "team_id", name=op.f("web_masters_team_members_pkey")),
    )
    op.create_table(
        "designer_task_difficulties",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("difficulty_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["difficulty_id"], ["difficulty_levels.id"], name=op.f("designer_task_difficulties_difficulty_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["designer_tasks.id"], name=op.f("designer_task_difficulties_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("task_id", "difficulty_id", name=op.f("designer_task_difficulties_pkey")),
    )
    op.create_table(
        "designer_task_edits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("solved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["designer_tasks.id"], name=op.f("designer_task_edits_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("designer_task_edits_pkey")),
    )
    op.create_table(
        "designer_task_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("buyer_id", sa.Integer(), nullable=True),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("assigned_designer_id", sa.Integer(), nullable=True),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("event_info", sa.Text(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("changed_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_designer_id"], ["designers.id"], name=op.f("designer_task_history_assigned_designer_id_fkey")
        ),
        sa.ForeignKeyConstraint(["buyer_id"], ["media_buyers.id"], name=op.f("designer_task_history_buyer_id_fkey")),
        sa.ForeignKeyConstraint(["changed_by_id"], ["users.id"], name=op.f("designer_task_history_changed_by_id_fkey")),
        sa.ForeignKeyConstraint(["lead_id"], ["designers.id"], name=op.f("designer_task_history_lead_id_fkey")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["designer_tasks.id"], name=op.f("designer_task_history_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("designer_task_history_pkey")),
    )
    op.create_table(
        "media_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=255), nullable=False),
        sa.Column("web_master_task_id", sa.Integer(), nullable=True),
        sa.Column("designer_task_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["designer_task_id"], ["designer_tasks.id"], name=op.f("media_files_designer_task_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["web_master_task_id"], ["web_master_tasks.id"], name=op.f("media_files_web_master_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("media_files_pkey")),
    )
    op.create_table(
        "task_corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("correction_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["designer_tasks.id"], name=op.f("task_corrections_task_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("task_corrections_pkey")),
    )
    op.create_table(
        "task_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("designer_task_id", sa.Integer(), nullable=True),
        sa.Column("web_master_task_id", sa.Integer(), nullable=True),
        sa.Column("evaluator_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(designer_task_id IS NOT NULL AND web_master_task_id IS NULL) OR (designer_task_id IS NULL AND web_master_task_id IS NOT NULL)",
            name=op.f("task_evaluations_check_one_task_reference_check"),
        ),
        sa.ForeignKeyConstraint(
            ["designer_task_id"],
            ["designer_tasks.id"],
            name=op.f("task_evaluations_designer_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["evaluator_id"], ["users.id"], name=op.f("task_evaluations_evaluator_id_fkey")),
        sa.ForeignKeyConstraint(
            ["web_master_task_id"],
            ["web_master_tasks.id"],
            name=op.f("task_evaluations_web_master_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_evaluations_pkey")),
    )
    op.create_table(
        "web_master_task_corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("correction_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["web_master_tasks.id"], name=op.f("web_master_task_corrections_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("web_master_task_corrections_pkey")),
    )
    op.create_table(
        "web_master_task_difficulties",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("difficulty_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["difficulty_id"],
            ["web_master_difficulty_levels.id"],
            name=op.f("web_master_task_difficulties_difficulty_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["web_master_tasks.id"], name=op.f("web_master_task_difficulties_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("task_id", "difficulty_id", name=op.f("web_master_task_difficulties_pkey")),
    )
    op.create_table(
        "web_master_task_edits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("solved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["web_master_tasks.id"], name=op.f("web_master_task_edits_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("web_master_task_edits_pkey")),
    )
    op.create_table(
        "web_master_task_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("buyer_id", sa.Integer(), nullable=True),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("assigned_web_master_id", sa.Integer(), nullable=True),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("event_info", sa.Text(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("changed_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_web_master_id"],
            ["web_masters.id"],
            name=op.f("web_master_task_history_assigned_web_master_id_fkey"),
        ),
        sa.ForeignKeyConstraint(["buyer_id"], ["media_buyers.id"], name=op.f("web_master_task_history_buyer_id_fkey")),
        sa.ForeignKeyConstraint(
            ["changed_by_id"], ["users.id"], name=op.f("web_master_task_history_changed_by_id_fkey")
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["web_masters.id"], name=op.f("web_master_task_history_lead_id_fkey")),
        sa.ForeignKeyConstraint(
            ["task_id"], ["web_master_tasks.id"], name=op.f("web_master_task_history_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("web_master_task_history_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_master_task_history")
    op.drop_table("web_master_task_edits")
    op.drop_table("web_master_task_difficulties")
    op.drop_table("web_master_task_corrections")
    op.drop_table("task_evaluations")
    op.drop_table("task_corrections")
    op.drop_table("media_files")
    op.drop_table("designer_task_history")
    op.drop_table("designer_task_edits")
    op.drop_table("designer_task_difficulties")
    op.drop_table("web_masters_team_members")
    op.drop_table("web_master_tasks")
    op.drop_table("media_buyers_team_members")
    op.drop_table("designers_team_members")
    op.drop_table("designer_tasks")
    op.drop_table("web_masters_teams")
    op.drop_table("media_buyers_teams")
    op.drop_table("designers_teams")
    op.drop_table("web_masters")
    op.drop_table("media_buyers")
    op.drop_table("designers")
    op.drop_table("admins")
    op.drop_table("web_master_task_types")
    op.drop_table("web_master_difficulty_levels")
    op.drop_table("users")
    op.drop_table("task_types")
    op.drop_table("difficulty_levels")
    # ### end Alembic commands ###
