"""add_keitaro_fields_to_creatives

Revision ID: 081eaa765de8
Revises: 36f242c392b7
Create Date: 2025-09-14 02:58:17.695774

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "081eaa765de8"
down_revision = "36f242c392b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("campaign_id", sa.Integer(), nullable=True))
    op.add_column("creatives", sa.Column("campaign_name", sa.String(length=200), nullable=True))
    op.add_column("creatives", sa.Column("stream_id", sa.Integer(), nullable=True))
    op.add_column("creatives", sa.Column("stream_name", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("creatives", "stream_name")
    op.drop_column("creatives", "stream_id")
    op.drop_column("creatives", "campaign_name")
    op.drop_column("creatives", "campaign_id")
    # ### end Alembic commands ###
