"""move_celebrities_from_creatives_to_tasks

Revision ID: 1d13f13173be
Revises: dd963849a1bd
Create Date: 2025-09-22 17:49:08.021931

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1d13f13173be"
down_revision = "dd963849a1bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "designer_task_celebrities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("celebrity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["celebrity_id"],
            ["celebrities.id"],
            name=op.f("designer_task_celebrities_celebrity_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["designer_tasks.id"], name=op.f("designer_task_celebrities_task_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("designer_task_celebrities_pkey")),
        sa.UniqueConstraint("task_id", "celebrity_id", name="ux_designer_task_celebrity_unique"),
    )
    op.drop_table("creative_celebrities")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creative_celebrities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("creative_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("celebrity_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["celebrity_id"], ["celebrities.id"], name="creative_celebrities_celebrity_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"], ["creatives.id"], name="creative_celebrities_creative_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="creative_celebrities_pkey"),
        sa.UniqueConstraint("creative_id", "celebrity_id", name="ux_creative_celebrity_unique"),
    )
    op.drop_table("designer_task_celebrities")
    # ### end Alembic commands ###
