"""Add creo field to keitaro_configs

Revision ID: f953814be582
Revises: 9e9f56f0bd6d
Create Date: 2025-09-23 20:03:27.035476

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f953814be582"
down_revision = "9e9f56f0bd6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("keitaro_configs", sa.Column("creo", sa.String(length=50), nullable=False, server_default="utm_id"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keitaro_configs", "creo")
    # ### end Alembic commands ###
