"""added archives restriction

Revision ID: e2eaf16873a7
Revises: f2ef9a4c4e00
Create Date: 2025-07-09 15:53:26.982439

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e2eaf16873a7"
down_revision = "f2ef9a4c4e00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_buyers_teams", sa.Column("allow_archives", sa.Boolean(), nullable=False, server_default=sa.text("false"))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_buyers_teams", "allow_archives")
    # ### end Alembic commands ###
