"""update_creative_fields_to_boolean_and_add_celebrity_titer

Revision ID: d411e9e4d832
Revises: 5d3f65c33135
Create Date: 2025-09-12 00:23:19.423510

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d411e9e4d832"
down_revision = "5d3f65c33135"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("celebrity_titer", sa.Boolean(), nullable=True))
    
    # Спочатку очищаємо дані в полях subtitles та plashka
    op.execute("UPDATE creatives SET subtitles = NULL WHERE subtitles IS NOT NULL")
    op.execute("UPDATE creatives SET plashka = NULL WHERE plashka IS NOT NULL")
    
    # Тепер змінюємо типи з USING клаузулою
    op.execute("ALTER TABLE creatives ALTER COLUMN subtitles TYPE BOOLEAN USING subtitles::boolean")
    op.execute("ALTER TABLE creatives ALTER COLUMN plashka TYPE BOOLEAN USING plashka::boolean")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "creatives", "plashka", existing_type=sa.Boolean(), type_=sa.VARCHAR(length=255), existing_nullable=True
    )
    op.alter_column("creatives", "subtitles", existing_type=sa.Boolean(), type_=sa.TEXT(), existing_nullable=True)
    op.drop_column("creatives", "celebrity_titer")
    # ### end Alembic commands ###
