"""Added soft delete for mb team

Revision ID: c6c4821e7f5f
Revises: 55e071fe989d
Create Date: 2025-06-12 10:49:40.873223

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6c4821e7f5f"
down_revision = "55e071fe989d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_buyers_teams", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_buyers_teams", "is_deleted")
    # ### end Alembic commands ###
