"""Update Creative model for multiple streams support

Revision ID: 75f1cf0b7b97
Revises: 081eaa765de8
Create Date: 2025-09-14 14:08:40.340433

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "75f1cf0b7b97"
down_revision = "081eaa765de8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("streams_data", sa.JSON(), nullable=True))
    op.drop_column("creatives", "stream_id")
    op.drop_column("creatives", "stream_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("stream_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column("creatives", sa.Column("stream_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("creatives", "streams_data")
    # ### end Alembic commands ###
