"""Added file_key column to media files

Revision ID: 5aecdbb85fe4
Revises: 4d508cb52984
Create Date: 2025-07-03 20:19:41.455636

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5aecdbb85fe4"
down_revision = "4d508cb52984"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_files", sa.Column("file_key", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_files", "file_key")
    # ### end Alembic commands ###
