"""added media buyer team verticals

Revision ID: f387812821bb
Revises: 5ae25ea7735d
Create Date: 2025-07-02 12:36:06.413488

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f387812821bb"
down_revision = "5ae25ea7735d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    verticaltype = sa.Enum("CRYPTO", "GAMBLING", "NUTRA", "GOOGLE", name="verticaltype")
    verticaltype.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "media_buyers_teams",
        sa.Column("vertical", verticaltype, nullable=False, server_default="CRYPTO"),
    )

    op.execute("UPDATE media_buyers_teams SET vertical = 'CRYPTO' WHERE vertical IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_buyers_teams", "vertical")
    op.execute("DROP TYPE verticaltype")
    # ### end Alembic commands ###
