"""added soft delete

Revision ID: 0eccb0aa2e35
Revises: 9d77f867f7fb
Create Date: 2025-07-29 11:49:48.058521

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0eccb0aa2e35"
down_revision = "9d77f867f7fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("web_master_tasks", sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("web_master_tasks", "is_deleted")
    # ### end Alembic commands ###
