"""refactor_creatives_celebrities_to_many_to_many

Revision ID: a1e27506a2f1
Revises: 75f1cf0b7b97
Create Date: 2025-09-15 16:23:10.774241

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1e27506a2f1"
down_revision = "75f1cf0b7b97"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creative_celebrities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creative_id", sa.Integer(), nullable=False),
        sa.Column("celebrity_id", sa.Integer(), nullable=False),
        sa.Column("titer", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["celebrity_id"],
            ["celebrities.id"],
            name=op.f("creative_celebrities_celebrity_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"], ["creatives.id"], name=op.f("creative_celebrities_creative_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("creative_celebrities_pkey")),
        sa.UniqueConstraint("creative_id", "celebrity_id", name="ux_creative_celebrity_unique"),
    )
    
    # Migrate existing data from creatives.celebrity_id and creatives.celebrity_titer to creative_celebrities
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO creative_celebrities (creative_id, celebrity_id, titer, created_at)
        SELECT id, celebrity_id, COALESCE(celebrity_titer, false), created_at
        FROM creatives 
        WHERE celebrity_id IS NOT NULL
    """))
    
    op.drop_constraint("creatives_celebrity_id_fkey", "creatives", type_="foreignkey")
    op.drop_column("creatives", "celebrity_id")
    op.drop_column("creatives", "celebrity_titer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("celebrity_titer", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column("creatives", sa.Column("celebrity_id", sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Migrate data back from creative_celebrities to creatives
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE creatives 
        SET celebrity_id = cc.celebrity_id, celebrity_titer = cc.titer
        FROM creative_celebrities cc
        WHERE creatives.id = cc.creative_id
    """))
    
    op.create_foreign_key("creatives_celebrity_id_fkey", "creatives", "celebrities", ["celebrity_id"], ["id"])
    op.drop_table("creative_celebrities")
    # ### end Alembic commands ###
