"""is_high_priority false to completed tasks

Revision ID: f2ef9a4c4e00
Revises: 8dcf333f11cd
Create Date: 2025-07-08 16:40:13.186658

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2ef9a4c4e00"
down_revision = "8dcf333f11cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE designer_tasks SET is_high_priority = FALSE WHERE task_status = 'COMPLETED';"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
