"""added geo codes

Revision ID: c95587fc2468
Revises: 140258104c76
Create Date: 2025-07-22 00:43:07.208887

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c95587fc2468"
down_revision = "140258104c76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("designer_tasks", sa.Column("geo_code", sa.String(length=2), nullable=True))
    op.add_column("designer_tasks", sa.Column("geo_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("designer_tasks", "geo_name")
    op.drop_column("designer_tasks", "geo_code")
    # ### end Alembic commands ###
