"""add_approach_field_to_creatives

Revision ID: f181f9439170
Revises: ce9a760242d8
Create Date: 2025-09-17 14:28:07.877689

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f181f9439170"
down_revision = "ce9a760242d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("creatives", sa.Column("approach", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("creatives", "approach")
    # ### end Alembic commands ###
