"""added fk cascade for deleted tasks

Revision ID: 8dcf333f11cd
Revises: 64841e0acee9
Create Date: 2025-07-07 14:47:59.594329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8dcf333f11cd"
down_revision = "64841e0acee9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("designer_task_difficulties_task_id_fkey", "designer_task_difficulties", type_="foreignkey")
    op.create_foreign_key(
        op.f("designer_task_difficulties_task_id_fkey"),
        "designer_task_difficulties",
        "designer_tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("media_files_designer_task_id_fkey", "media_files", type_="foreignkey")
    op.create_foreign_key(
        op.f("media_files_designer_task_id_fkey"),
        "media_files",
        "designer_tasks",
        ["designer_task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("media_files_designer_task_id_fkey"), "media_files", type_="foreignkey")
    op.create_foreign_key(
        "media_files_designer_task_id_fkey", "media_files", "designer_tasks", ["designer_task_id"], ["id"]
    )
    op.drop_constraint(
        op.f("designer_task_difficulties_task_id_fkey"), "designer_task_difficulties", type_="foreignkey"
    )
    op.create_foreign_key(
        "designer_task_difficulties_task_id_fkey", "designer_task_difficulties", "designer_tasks", ["task_id"], ["id"]
    )
    # ### end Alembic commands ###
