"""add_creo_field_to_users

Revision ID: d452d25177f0
Revises: 03087aaed981
Create Date: 2025-10-08 23:06:49.350554

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d452d25177f0"
down_revision = "03087aaed981"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("creo", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "creo")
    # ### end Alembic commands ###
