"""fix task_notes indexes

Revision ID: 64841e0acee9
Revises: 62b5d7cdd6ed
Create Date: 2025-07-04 15:23:24.597555

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "64841e0acee9"
down_revision = "62b5d7cdd6ed"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("TRUNCATE TABLE task_notes RESTART IDENTITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_notes", sa.Column("is_team_note", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.alter_column("task_notes", "author_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "task_notes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "task_notes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.drop_constraint("uq_note_designer_task_author", "task_notes", type_="unique")
    op.drop_constraint("uq_note_webmaster_task_author", "task_notes", type_="unique")
    op.create_unique_constraint("ux_note_webmaster_task_author", "task_notes", ["web_master_task_id", "author_id"])
    op.create_unique_constraint("ux_task_author_note", "task_notes", ["designer_task_id", "author_id"])
    op.create_index(
        "ux_task_team_note",
        "task_notes",
        ["designer_task_id"],
        unique=True,
        postgresql_where=sa.text("is_team_note = TRUE"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ux_task_team_note", table_name="task_notes", postgresql_where=sa.text("is_team_note = TRUE"))
    op.drop_constraint("ux_task_author_note", "task_notes", type_="unique")
    op.drop_constraint("ux_note_webmaster_task_author", "task_notes", type_="unique")
    op.create_unique_constraint("uq_note_webmaster_task_author", "task_notes", ["web_master_task_id", "author_id"])
    op.create_unique_constraint("uq_note_designer_task_author", "task_notes", ["designer_task_id", "author_id"])
    op.alter_column(
        "task_notes",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "task_notes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column("task_notes", "author_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("task_notes", "is_team_note")
    # ### end Alembic commands ###
