"""added uuid to designer tasks and web master tasks

Revision ID: 76d013ed7c7e
Revises: ab280f03175a
Create Date: 2025-06-25 22:55:20.386814

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76d013ed7c7e"
down_revision = "ab280f03175a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("designer_tasks", sa.Column("uuid", sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f("designer_tasks_uuid_key"), "designer_tasks", ["uuid"])
    op.add_column("web_master_tasks", sa.Column("uuid", sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f("web_master_tasks_uuid_key"), "web_master_tasks", ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("web_master_tasks_uuid_key"), "web_master_tasks", type_="unique")
    op.drop_column("web_master_tasks", "uuid")
    op.drop_constraint(op.f("designer_tasks_uuid_key"), "designer_tasks", type_="unique")
    op.drop_column("designer_tasks", "uuid")
    # ### end Alembic commands ###
