"""added unique constraint for notes

Revision ID: 4d508cb52984
Revises: f387812821bb
Create Date: 2025-07-03 14:41:24.394224

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d508cb52984"
down_revision = "f387812821bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_notes", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint("uq_note_designer_task_author", "task_notes", ["designer_task_id", "author_id"])
    op.create_unique_constraint("uq_note_webmaster_task_author", "task_notes", ["web_master_task_id", "author_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_note_webmaster_task_author", "task_notes", type_="unique")
    op.drop_constraint("uq_note_designer_task_author", "task_notes", type_="unique")
    op.drop_column("task_notes", "updated_at")
    # ### end Alembic commands ###
