"""added task notes

Revision ID: 5ae25ea7735d
Revises: da6d050161da
Create Date: 2025-07-01 16:33:36.734768

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ae25ea7735d"
down_revision = "da6d050161da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("designer_task_id", sa.Integer(), nullable=True),
        sa.Column("web_master_task_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(designer_task_id IS NOT NULL AND web_master_task_id IS NULL) OR (designer_task_id IS NULL  AND web_master_task_id IS NOT NULL)",
            name=op.f("task_notes_check_one_task_reference_check"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("task_notes_author_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["designer_task_id"],
            ["designer_tasks.id"],
            name=op.f("task_notes_designer_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["web_master_task_id"],
            ["web_master_tasks.id"],
            name=op.f("task_notes_web_master_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_notes_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_notes")
    # ### end Alembic commands ###
