"""added allow_view_team_tasks for media buyer

Revision ID: 27a3694a0e79
Revises: ab280f03175a
Create Date: 2025-06-20 16:35:21.071230

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27a3694a0e79"
down_revision = "ab280f03175a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_buyers",
        sa.Column("allow_view_team_tasks", sa.Boolean(), nullable=False, server_default=sa.false())
    )    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_buyers", "allow_view_team_tasks")
    # ### end Alembic commands ###
